events_events:
    resource: "@EventsEventsBundle/Controller/"
    type:     annotation
    prefix:   /

# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
